import type { BoardAssetBundle } from './types';

export const BOARD_ASSETS: Record<string, BoardAssetBundle> = {
  nano: {
    vendor: 'Arduino',
    docsUrl: 'https://docs.arduino.cc/hardware/nano/',
    pinoutUrl: 'https://docs.arduino.cc/resources/pinouts/A000005-full-pinout.pdf',
    schematicUrl: 'https://docs.arduino.cc/resources/schematics/A000005-schematics.pdf',
    cad3dUrl: 'https://docs.arduino.cc/resources/cad/A000005-cad-files.zip',
    localDocsPath: '/board-assets/nano/docs.html',
    localPinoutPath: '/board-assets/nano/pinout.pdf',
    localSchematicPath: '/board-assets/nano/schematic.pdf',
    localCadPath: '/board-assets/nano/cad.zip',
    notes: ['Classic Nano (ATmega328P).'],
  },
  nano_every: {
    vendor: 'Arduino',
    docsUrl: 'https://docs.arduino.cc/hardware/nano-every/',
    pinoutUrl: 'https://docs.arduino.cc/resources/pinouts/ABX00028-full-pinout.pdf',
    schematicUrl: 'https://docs.arduino.cc/resources/schematics/ABX00028-schematics.pdf',
    cad3dUrl: 'https://docs.arduino.cc/resources/cad/ABX00028-cad-files.zip',
    localDocsPath: '/board-assets/nano_every/docs.html',
    localPinoutPath: '/board-assets/nano_every/pinout.pdf',
    localSchematicPath: '/board-assets/nano_every/schematic.pdf',
    localCadPath: '/board-assets/nano_every/cad.zip',
  },
  nano_33_iot: {
    vendor: 'Arduino',
    docsUrl: 'https://docs.arduino.cc/hardware/nano-33-iot/',
    pinoutUrl: 'https://docs.arduino.cc/resources/pinouts/ABX00027-full-pinout.pdf',
    schematicUrl: 'https://docs.arduino.cc/resources/schematics/ABX00027-schematics.pdf',
    cad3dUrl: 'https://docs.arduino.cc/resources/cad/ABX00027-cad-files.zip',
    localDocsPath: '/board-assets/nano_33_iot/docs.html',
    localPinoutPath: '/board-assets/nano_33_iot/pinout.pdf',
    localSchematicPath: '/board-assets/nano_33_iot/schematic.pdf',
    localCadPath: '/board-assets/nano_33_iot/cad.zip',
  },
  nano_rp2040_connect: {
    vendor: 'Arduino',
    docsUrl: 'https://docs.arduino.cc/hardware/nano-rp2040-connect/',
    pinoutUrl: 'https://docs.arduino.cc/resources/pinouts/ABX00053-full-pinout.pdf',
    schematicUrl: 'https://docs.arduino.cc/resources/schematics/ABX00053-schematics.pdf',
    cad3dUrl: 'https://docs.arduino.cc/resources/cad/ABX00053-cad-files.zip',
    localDocsPath: '/board-assets/nano_rp2040_connect/docs.html',
    localPinoutPath: '/board-assets/nano_rp2040_connect/pinout.pdf',
    localSchematicPath: '/board-assets/nano_rp2040_connect/schematic.pdf',
    localCadPath: '/board-assets/nano_rp2040_connect/cad.zip',
  },
  nano_esp32: {
    vendor: 'Arduino',
    docsUrl: 'https://docs.arduino.cc/hardware/nano-esp32/',
    pinoutUrl: 'https://docs.arduino.cc/resources/pinouts/ABX00083-full-pinout.pdf',
    schematicUrl: 'https://docs.arduino.cc/resources/schematics/ABX00083-schematics.pdf',
    cad3dUrl: 'https://docs.arduino.cc/resources/cad/ABX00083-cad-files.zip',
    localDocsPath: '/board-assets/nano_esp32/docs.html',
    localPinoutPath: '/board-assets/nano_esp32/pinout.pdf',
    localSchematicPath: '/board-assets/nano_esp32/schematic.pdf',
    localCadPath: '/board-assets/nano_esp32/cad.zip',
    notes: ['Uses ESP32-S3 based NORA module.'],
  },
  uno: {
    vendor: 'Arduino',
    docsUrl: 'https://docs.arduino.cc/hardware/uno-rev3/',
    pinoutUrl: 'https://docs.arduino.cc/resources/pinouts/A000066-full-pinout.pdf',
    schematicUrl: 'https://docs.arduino.cc/resources/schematics/A000066-schematics.pdf',
    cad3dUrl: 'https://docs.arduino.cc/resources/cad/A000066-cad-files.zip',
    localDocsPath: '/board-assets/uno/docs.html',
    localPinoutPath: '/board-assets/uno/pinout.pdf',
    localSchematicPath: '/board-assets/uno/schematic.pdf',
    localCadPath: '/board-assets/uno/cad.zip',
  },
  teensy40: {
    vendor: 'PJRC',
    docsUrl: 'https://www.pjrc.com/store/teensy40.html',
    pinoutUrl: 'https://www.pjrc.com/teensy/pinout.html',
    localDocsPath: '/board-assets/teensy40/docs.html',
    localPinoutPath: '/board-assets/teensy40/pinout.html',
    notes: ['Use PJRC pinout card for exact alternate-function mapping.'],
  },
  teensy41: {
    vendor: 'PJRC',
    docsUrl: 'https://www.pjrc.com/store/teensy41.html',
    pinoutUrl: 'https://www.pjrc.com/teensy/pinout.html',
    localDocsPath: '/board-assets/teensy41/docs.html',
    localPinoutPath: '/board-assets/teensy41/pinout.html',
    notes: ['Use PJRC pinout card for exact alternate-function mapping.'],
  },
  esp32_devkitc_v4: {
    vendor: 'Espressif',
    docsUrl: 'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html',
    schematicUrl: 'https://dl.espressif.com/dl/schematics/esp32_devkitc_v4-sch.pdf',
    cadStepUrl: 'https://www.snapeda.com/parts/ESP32-DevKitC/Espressif%20Systems/view-part/',
    localDocsPath: '/board-assets/esp32_devkitc_v4/docs.html',
    localSchematicPath: '/board-assets/esp32_devkitc_v4/schematic.pdf',
    notes: ['Board revisions can vary by module vendor; verify silk + module marking.'],
  },
  esp32_devkitc_v3: {
    vendor: 'Espressif',
    docsUrl: 'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html',
    schematicUrl: 'https://dl.espressif.com/dl/schematics/esp32_devkitc_v4-sch.pdf',
    localDocsPath: '/board-assets/esp32_devkitc_v3/docs.html',
    localSchematicPath: '/board-assets/esp32_devkitc_v3/schematic.pdf',
    notes: ['V3 and V4 commonly share logical pin naming but may differ physically.'],
  },
  esp32_s3_devkitc_1: {
    vendor: 'Espressif',
    docsUrl: 'https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-devkitc-1/user_guide.html',
    schematicUrl: 'https://dl.espressif.com/dl/schematics/esp32-s3-devkitc-1-v1.0-sch.pdf',
    cadStepUrl: 'https://www.snapeda.com/parts/ESP32-S3-DevKitC-1/Espressif%20Systems/view-part/',
    localDocsPath: '/board-assets/esp32_s3_devkitc_1/docs.html',
    localSchematicPath: '/board-assets/esp32_s3_devkitc_1/schematic.pdf',
  },
};

export const MIRRORED_BOARD_ASSET_PATHS = new Set<string>([
  '/board-assets/nano/docs.html',
  '/board-assets/nano/pinout.pdf',
  '/board-assets/nano/schematic.pdf',
  '/board-assets/nano_every/docs.html',
  '/board-assets/nano_every/pinout.pdf',
  '/board-assets/nano_every/schematic.pdf',
  '/board-assets/nano_esp32/docs.html',
  '/board-assets/nano_esp32/pinout.pdf',
  '/board-assets/nano_esp32/schematic.pdf',
  '/board-assets/uno/docs.html',
  '/board-assets/uno/pinout.pdf',
  '/board-assets/uno/schematic.pdf',
  '/board-assets/esp32_devkitc_v4/docs.html',
  '/board-assets/esp32_devkitc_v4/schematic.pdf',
  '/board-assets/teensy40/docs.html',
  '/board-assets/teensy40/pinout.html',
  '/board-assets/teensy41/docs.html',
  '/board-assets/teensy41/pinout.html',
]);
