#pragma once

/*
  UpRight.os lean profile flags for balance_mvp_v2_core.
  Goal: fast tuning loop on Nano with minimal non-essential features.
*/

#define UPRIGHT_PROFILE_TEST_MINIMAL 1
#define UPRIGHT_PROFILE_LAB_FULL 2
#define UPRIGHT_PROFILE_FIELD_HARDENED 3

#ifndef UPRIGHT_PROFILE
#define UPRIGHT_PROFILE UPRIGHT_PROFILE_TEST_MINIMAL
#endif

#define FEAT_FIXED_RATE_LOOP 1
#define FEAT_SAFETY_STATE_MACHINE 1
#define FEAT_ESTOP_LATCH 1
#define FEAT_WATCHDOG 1
#define FEAT_SENSOR_PLAUSIBILITY 1
#define FEAT_NO_HEAP_RT_PATH 1

#if UPRIGHT_PROFILE == UPRIGHT_PROFILE_TEST_MINIMAL
  #define FEAT_ADV_TELEMETRY 0
  #define FEAT_VERBOSE_DIAGNOSTICS 1
  #define FEAT_AUTOTUNE_HELPERS 0
  #define FEAT_COHEN_COON_CMD 0
  #define FEAT_TRANSFER_FN_CMD 0
  #define FEAT_BURST_LOGGING 0
  #define FEAT_EEPROM_CONFIG 1
  #define FEAT_ADAPTIVE_GAINS 0
  #define FEAT_AUTORUN_CMD 1
  #define FEAT_BOOT_AUTORUN 1
  #define FEAT_PREARM_CMD 0
  #define FEAT_IMU_SERVICE_CMDS 0
  #define ENCODER_STALE_ARM_GRACE_MS 1800U
  #define ENCODER_STALE_TIMEOUT_MS 700U
  #define ENCODER_STALE_OUT_MIN 85.0f
  #define LOOP_OVERRUN_ARM_GRACE_MS 2000U
  #define LOOP_OVERRUN_CONSEC_LIMIT 8U
  #define LOOP_OVERRUN_LATCH_ENABLED 0
#elif UPRIGHT_PROFILE == UPRIGHT_PROFILE_LAB_FULL
  #define FEAT_ADV_TELEMETRY 1
  #define FEAT_VERBOSE_DIAGNOSTICS 1
  #define FEAT_AUTOTUNE_HELPERS 1
  #define FEAT_COHEN_COON_CMD 1
  #define FEAT_TRANSFER_FN_CMD 1
  #define FEAT_BURST_LOGGING 1
  #define FEAT_EEPROM_CONFIG 1
  #define FEAT_ADAPTIVE_GAINS 1
  #define FEAT_AUTORUN_CMD 1
  #define FEAT_BOOT_AUTORUN 1
  #define FEAT_PREARM_CMD 1
  #define FEAT_IMU_SERVICE_CMDS 1
  #define ENCODER_STALE_ARM_GRACE_MS 1600U
  #define ENCODER_STALE_TIMEOUT_MS 650U
  #define ENCODER_STALE_OUT_MIN 80.0f
  #define LOOP_OVERRUN_ARM_GRACE_MS 1500U
  #define LOOP_OVERRUN_CONSEC_LIMIT 6U
  #define LOOP_OVERRUN_LATCH_ENABLED 1
#elif UPRIGHT_PROFILE == UPRIGHT_PROFILE_FIELD_HARDENED
  #define FEAT_ADV_TELEMETRY 1
  #define FEAT_VERBOSE_DIAGNOSTICS 0
  #define FEAT_AUTOTUNE_HELPERS 0
  #define FEAT_COHEN_COON_CMD 0
  #define FEAT_TRANSFER_FN_CMD 0
  #define FEAT_BURST_LOGGING 1
  #define FEAT_EEPROM_CONFIG 1
  #define FEAT_ADAPTIVE_GAINS 0
  #define FEAT_AUTORUN_CMD 1
  #define FEAT_BOOT_AUTORUN 1
  #define FEAT_PREARM_CMD 1
  #define FEAT_IMU_SERVICE_CMDS 0
  #define ENCODER_STALE_ARM_GRACE_MS 500U
  #define ENCODER_STALE_TIMEOUT_MS 500U
  #define ENCODER_STALE_OUT_MIN 70.0f
  #define LOOP_OVERRUN_ARM_GRACE_MS 500U
  #define LOOP_OVERRUN_CONSEC_LIMIT 5U
  #define LOOP_OVERRUN_LATCH_ENABLED 1
#else
  #error "Unknown UPRIGHT_PROFILE value"
#endif

#define LOOP_HZ 200U
#define LOOP_PERIOD_US (1000000UL / LOOP_HZ)
#define STATUS_PERIOD_MS 100U

#define MAX_CONTROL_STEP_US 3500U
