export const strings = {
  app: {
    title: 'UpRight.os Operations Console',
    buildLabel: 'REBUILD-V1',
    connected: 'connected',
    disconnected: 'disconnected',
    setupTab: 'Setup',
    tuneTab: 'Tune',
    ideTab: 'IDE',
    compactOn: 'Compact On',
    compactOff: 'Compact Off',
  },
  tune: {
    title: 'Calibration + Tuning',
    subtitle: 'primary balancing controls',
    refresh: 'Refresh',
    compatProbe: 'Run Compatibility Probe',
    syncFromBot: 'Sync From Bot',
    applyPid: 'Apply PID',
    applyMotion: 'Apply Motion',
    applySetpoint: 'Apply Setpoint',
    prepareArm: 'Prepare Arm',
    confirmArm: 'Confirm Arm',
    disarm: 'Disarm',
    clearFault: 'Clear Fault',
    calZero: 'Cal Zero',
    saveCfg: 'Save Config',
    estopLatch: 'EMERGENCY STOP',
    estopReset: 'RESET',
    mode: 'Mode',
    angle: 'Angle',
    estop: 'E-Stop',
    compat: 'Compat',
    setpoint: 'Setpoint Deg',
  },
  ide: {
    title: 'Firmware IDE',
    subtitle: 'full arduino-cli workspace',
  },
  playground: {
    title: 'Iteration Playground',
    subtitle: 'phase 1-4 tooling in-app',
    traceTitle: 'Trace Replay',
    runTrace: 'Run Trace Replay',
    sweepTitle: 'Parameter Sweep',
    runSweep: 'Run Sweep',
  },
  workbench: {
    title: 'Firmware Workbench',
    subtitle: 'arduino-cli pipeline',
    tabSketch: 'Sketch',
    tabBoard: 'Board / Build',
    tabSerial: 'Serial',
    openSerialDock: 'Open Serial Dock',
    hideSerialDock: 'Hide Serial Dock',
    openSerialWindow: 'Open in Window',
    closeSerialDock: 'Close Dock',
    sketchFile: 'Sketch File',
    uploadSketchFile: 'Upload Sketch File',
    sketchUploadHint: 'Upload loads into editor only. Click Save Sketch to write to disk path above.',
    loadSketch: "Pull Board's Current Sketch",
    saveSketch: 'Save Sketch',
    saveSketchConfirmTitle: 'Confirm Sketch Overwrite',
    saveSketchConfirmSubtitle: 'Saving will overwrite the file at this exact path.',
    saveSketchConfirmAcknowledge: 'I understand this will overwrite the current file on disk.',
    saveSketchConfirmAction: 'Overwrite File',
    checkCli: 'Check CLI',
    installCli: 'Install CLI',
    scanBoards: 'Scan Boards',
    selectBoardPortTitle: 'Select Board and Serial Port',
    selectBoardPortSubtitle: 'Choose detected hardware target and communication path before verify/upload.',
    boardFqbn: 'Board (FQBN)',
    boardDetected: 'Detected',
    port: 'Port',
    sketchFolder: 'Sketch Folder',
    pickSketchFolder: 'Pick Folder',
    compile: 'Verify',
    upload: 'Flash',
    guardedFlash: 'Guarded Flash',
    unifiedTitle: 'Unified Scaffold Generator',
    unifiedSubtitle: 'Generate a standardized sketch package from a board/pin profile JSON.',
    unifiedSketchName: 'Generated Sketch Name',
    unifiedProfileJson: 'Unified Profile JSON',
    generateUnified: 'Generate Unified Sketch',
    recommended: 'Recommended',
    state: 'State',
    cli: 'CLI',
    pass: 'PASS',
    fail: 'FAIL',
    serialSubtitle: 'Send raw serial commands and tail lines from the firmware.',
    serialPlaceholder: 'e.g. GET or PID 31 0.05 1.05',
    send: 'Send',
    showCommands: 'Show Commands',
    refreshTail: 'Refresh Tail',
  },
  codex: {
    title: 'Codex',
    subtitle: 'assistant workspace',
    accountLoggedIn: 'account logged in',
    accountLoggedOut: 'account not logged in',
    bridgeOnline: 'bridge online',
    bridgeOffline: 'bridge offline',
    keySynced: 'openai key synced',
    keyMissing: 'openai key missing',
    model: 'model',
    signinPrompt: 'First, log in to your UpRight.os Account.',
    forgotPassword: 'Forgot / Reset Password',
    resetEmail: 'Account Email',
    requestResetCode: 'Request Reset Code',
    resetToken: 'Reset Token',
    newPassword: 'New Password',
    applyPasswordReset: 'Apply Password Reset',
    closeReset: 'Close Reset Form',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    working: 'Working...',
    createAccount: 'Create Account',
    signedInAs: 'Signed in as',
    noSavedKey: 'No OpenAI key saved yet.',
    openAiApiKey: 'OpenAI API Key',
    saveKey: 'Save OpenAI Key',
    deleteKey: 'Delete OpenAI Key',
    settings: 'Settings',
    closeSettings: 'Close Settings',
    revealLastChats: 'Reveal Last Chats',
    hideLastChats: 'Hide Last Chats',
    startNewChat: 'Start New Chat',
    recentChats: 'Recent Chats',
    logout: 'Logout',
    noChatHistory: 'No chat history yet.',
    chatPlaceholder: 'Ask Codex about tuning, logs, safety, or next steps...',
    thinking: 'Thinking...',
    send: 'Send',
    enableChatHint: 'Save an OpenAI key above to enable Codex chat.',
    bridgeWaitHint: 'Bridge is offline. Start/reconnect bridge, then retry login/chat.',
    assistantProfile: 'Assistant Profile',
    noProfiles: 'No profiles',
    profileLabel: 'Profile Label',
    profileDescription: 'Profile Description',
    profileInstructions: 'Prompt Instructions',
    allowAutoApply: 'Allow auto-apply from assistant actions',
    saveProfile: 'Save Profile',
    activateProfile: 'Activate',
    profileLockedHint: 'Profile editing is locked in-app. Update via local repository/Codex only.',
  },
  hud: {
    title: 'Live Input HUDs',
    subtitle: 'telemetry contract visibility',
    contractOk: 'OK',
    contractMissing: 'MISSING',
    filteredAngle: 'Filtered Angle',
    rawAngle: 'Raw Angle',
    gyroRate: 'Gyro Rate',
    output: 'Output',
    wheelPos: 'Wheel Pos',
    setpoint: 'Setpoint',
    pidError: 'PID Error',
    innovation: 'Kalman Innovation',
    clampState: 'Clamp State',
    loopFeed: 'Loop Feed',
    contract: 'Telemetry Contract',
  },
  status: {
    clear: 'CLEAR',
    latched: 'LATCHED',
    untested: 'UNTESTED',
    pass: 'PASS',
    fail: 'FAIL',
  },
  modal: {
    title: 'Guarded Flash Preflight',
    subtitle: 'Complete all checks before flashing.',
    ideClosed: 'Arduino IDE / Serial Monitor is closed',
    botSafe: 'Robot is in safe posture (wheels clear / supported)',
    portCorrectPrefix: 'Selected port is correct',
    powerExpected: 'Power configuration matches your upload plan (USB-only vs external battery)',
    cancel: 'Cancel',
    start: 'Start Guarded Flash',
  },
  v2Readiness: {
    title: 'Calibration Readiness (Phase 1 + Phase 2)',
    subtitle: 'Core calibration and advanced anti-drift capability status',
    v1Status: 'Phase 1 (Core)',
    v2Status: 'Phase 2 (Advanced)',
    missingFields: 'Missing Phase 2 Fields',
    presentFields: 'Present Advanced Fields',
    recommendedAction: 'Recommended Next Step',
    pass: 'PASS',
    warn: 'NOT READY',
    fail: 'FAIL',
    noData: 'No telemetry data',
    checksTitle: 'Readiness Checks',
    checkLabels: {
      v1_required_fields: 'Phase 1 Required Fields',
      v2_readiness_fields: 'Phase 2 Required Fields',
      v2_optional_fields: 'Advanced Optional Fields',
      calibration_data: 'Calibration Data',
      outer_loop_ready: 'Outer Loop Ready',
      telemetry_available: 'Telemetry Available',
      phase1_core_ready: 'Phase 1 Core Ready',
      phase2_advanced_ready: 'Phase 2 Advanced Ready',
    },
  },
  firmwareDocs: {
    title: 'Auto-Generated Firmware Architecture Docs',
    subtitle: 'Firmware Design Pack with standard artifact names',
    contractNote: 'All artifacts are generated from the same canonical hardware/telemetry command contracts used by Setup, IDE, and Tune.',
    generate: 'Generate Docs Pack',
    view: 'View Docs',
    viewerTitle: 'Firmware Architecture Docs',
    closeViewer: 'Close Viewer',
    noDocs: 'No docs generated yet. Generate a docs pack first.',
    artifact: 'Artifact',
    name: 'Standard Name',
    purpose: 'Purpose',
    controlFlow: 'Control Flow Diagram',
    controlFlowName: 'control_flow.mmd',
    controlFlowPurpose: 'Mermaid flowchart of setup()/loop() processing path.',
    stateMachine: 'State Machine Diagram',
    stateMachineName: 'state_machine.mmd',
    stateMachinePurpose: 'Mermaid stateDiagram-v2 of modes and transitions (SAFE_IDLE, ARMED, BALANCING).',
    hardwareBlock: 'Hardware Block Diagram',
    hardwareBlockName: 'hardware_block.mmd',
    hardwareBlockPurpose: 'Mermaid graph of MCU, IMU, motor driver, encoders, and interconnects.',
    pinMapping: 'Pin Mapping Diagram',
    pinMappingName: 'pin_mapping.mmd',
    pinMappingPurpose: 'Mermaid graph/classDiagram mapping MCU pins to component signals.',
    pinTable: 'Pin Assignment Table',
    pinTableName: 'pin_assignment.md',
    pinTablePurpose: 'Canonical pin/source-of-truth table: pin, signal, direction, component, notes.',
    commandMap: 'Command/API Map',
    commandMapName: 'command_api_map.md',
    commandMapPurpose: 'Serial commands supported and which config/state each command changes.',
  },
};
